### ISSUE TITLE
能够分享一下具体的环境配置吗？

### ISSUE THREAD

**Issue by RingoTC** [YibinShen/MultiMath#1]
因为ltp的原因，只能使用Python 3.6的环境。
但是在实际运行过程中，遇到了很多版本问题，比如cuda和pytorch、gensim和numpy和scipy等等，能否分享一下你们做实验的时候的具体的实验环境？

**Comment by YibinShen** [comment]
cuda 10.2
pytorch 1.4.0
gensim 3.8.0
numpy&nbsp;1.19.5
scipy&nbsp;1.5.4
numpy和scipy可能不是当初的版本，因为后面装了其他包更新了这两个包的版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YibinShen/MultiMath"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月6日(星期二) 下午4:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[YibinShen/MultiMath] 能够分享一下具体的环境配置吗？ (#1)





 
因为ltp的原因，�只能使用Python 3.6的环境。
 但是在实际运行过程中，遇到了很多版本问题，比如cuda和pytorch、gensim和numpy和scipy等等，能否分享一下你们做实验的时候的具体的实验环境？

**Comment by RingoTC** [comment]
好的 感谢。
